### ISSUE TITLE
deploy-playground.yml broken since #1026: copies WASM to wrong directory, TS2307 fails playground build

### ISSUE THREAD

**Issue by unchidev** [koedame/chordsketch#1050]
## Problem

`.github/workflows/deploy-playground.yml` has been failing on every push to `main` since 2026-04-07 06:07Z, breaking GitHub Pages deploys silently.

The current step at line 41-45:

```yaml
- name: Build WASM
  run: wasm-pack build crates/wasm --release --target web

- name: Copy WASM artifacts to npm package
  run: cp crates/wasm/pkg/chordsketch_wasm* packages/npm/
```

writes the WASM artifacts directly into `packages/npm/` (root). But after PR #1026 introduced the dual-package layout, the playground imports from the new `web/` subdirectory (`packages/playground/src/main.ts:8`):

```ts
import init, * as wasm from '../../npm/web/chordsketch_wasm.js';
```

So `tsc` fails with:

```
src/main.ts(8,8): error TS2307: Cannot find module '../../npm/web/chordsketch_wasm.js' or its corresponding type declarations.
```

Confirmed in 3 consecutive failing runs:
- [24067060204](https://github.com/koedame/chordsketch/actions/runs/24067060204) (commit 0991ae9)
- [24092616984](https://github.com/koedame/chordsketch/actions/runs/24092616984) (commit b8c74db)
- [24093720848](https://github.com/koedame/chordsketch/actions/runs/24093720848) (commit 40dbfb3)

The last successful deploy was 032b03d on 2026-04-06 17:18Z, so https://koedame.github.io/chordsketch/ is currently serving a stale build.

## Root cause

PR #1026 changed the npm package's directory layout (added `web/` and `node/` subdirectories with their own `package.json` to declare `type: module` vs `commonjs`), and updated:
- `packages/npm/scripts/build.mjs` (canonical local build)
- `.github/workflows/npm-publish.yml` (publish workflow)

but missed `.github/workflows/deploy-playground.yml`.

## Fix

Replace the broken `Build WASM` + `Copy WASM artifacts` steps with a single call to the canonical build script (`packages/npm/scripts/build.mjs` aka `npm run build` from `packages/npm`). This already produces the correct dual-package layout and is mirrored byte-for-byte by `npm-publish.yml`. `Setup Node.js` must be moved earlier so node is on PATH before invoking the build script.

This deduplicates the build logic — `deploy-playground.yml` no longer carries its own copy of the wasm-pack invocation, so future layout changes only need to touch `build.mjs` (and `npm-publish.yml`, which has its own copy because it interleaves `npm version` between build and publish).

## Acceptance criteria

- [ ] `deploy-playground.yml` build step succeeds on `main` HEAD
- [ ] GitHub Pages serves a fresh build (verify by checking the deployed URL after the first successful run)
- [ ] No regression in `npm-publish.yml` or `packages/npm/scripts/build.mjs` (they remain the source of truth)

## Phase

Phase 20 — surfaced by Phase Completion Gate review on #862.
